Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu2204"

    config.vm.define "brunmartS" do |server|
        server.vm.hostname = "brunmartS"
        server.vm.network "private_network", ip: "192.168.56.110"

        server.vm.provider "virtualbox" do |vb|
            vb.memory = 2048
            vb.cpus = 1
        end

        server.vm.provision "shell", path: "scripts/install_k3s.sh"
    end
end